//Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST= "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//Clear error

export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_REQUEST= "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

//user loading

export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_REQUEST= "USER_LOADING_REQUEST";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";


//logout

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_REQUEST= "LOGOUT_REQUEST";
export const LOGOUT_FAILURE = "LOGOUT_FAILURURE";

//clear error

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REQUEST= "REGISTER_REQUEST";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//posts write

export const POST_WRITE_SUCCESS = "POST_WRITE_SUCCESS";
export const POST_WRITE_REQUEST= "POST_WRITE_REQUEST";
export const POST_WRITE_FAILURE = "POST_WRITE_FAILURE";

//posts loading

export const POSTS_LOADING_SUCCESS = "POSTS_LOADING_SUCCESS";
export const POSTS_LOADING_REQUEST= "POSTS_LOADING_REQUEST";
export const POSTS_LOADING_FAILURE = "POSTS_LOADING_FAILURE";